title:  kNews Space
tagline:  Rocket Launch and Space News

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'watchknews'

google-ID: 'UA-59274965-1'

menu:
- {name: 'News', path: 'menu', url: '../news/index.html'}
- {name: 'Blog', path: 'menu', url: '../blog/index.html'}
- {name: 'KSP Crafts', path: 'menu', url: 'crafts.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/kNewsSpace'}
- {icon: 'youtube', link: 'https://youtube.com/c/kNewsSpace'}
- {icon: 'envelope', link: 'mailto:kNewsSpace@outlook.com'}
